# Основная информация
site_name: leetcodeAndPython
site_url: https://github.com/qqracha/leetcodeAndPython

# Репозиторий
repo_name: leetcodeAndPython
repo_url: https://github.com/qqracha/leetcodeAndPython

# shadcn
theme:
  name: shadcn
  show_title: true # show the title in the top bar
  show_stargazers: true # show the stargazers in the top bar
  pygments_style: # default styles 
        light: shadcn-light
        dark: github-dark
  topbar_sections: true # NEW!
  show_datetime: true 

# Плагины
plugins:
  - search

# Markdown расширения
markdown_extensions:
  - admonition
  - attr_list
  - codehilite
  - pymdownx.highlight
  - shadcn.extensions.codexec
  - pymdownx.superfences
  - pymdownx.blocks.caption
  - pymdownx.blocks.details
  - pymdownx.blocks.tab
  - pymdownx.progressbar
  - pymdownx.arithmatex:
      generic: true # required to work
  - pymdownx.snippets:
      base_path: ["."]

extra_css:
  - stylescheets/extra.css