site_name: leetcodeAndPython
site_url: https://qqracha.github.io/leetcodeAndPython/

repo_name: leetcodeAndPython
repo_url: https://github.com/qqracha/leetcodeAndPython
edit_uri: edit/main/docs/

theme:
  name: material
  font:
    text: Roboto
    code: JetBrains Mono
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.footer

plugins:
  - search

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.blocks.caption
  - pymdownx.blocks.details
  - pymdownx.blocks.tab
  - pymdownx.progressbar
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.snippets:
      base_path: ["."]
  - toc:
      permalink: '#'
      permalink_title: "meow"

extra_css:
  - stylesheets/extra.css
  - stylesheets/pygments-custom.css